# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/wandb',
                'doc_host': 'https://Lekja00160612.github.io',
                'git_url': 'https://github.com/Lekja00160612/wandb',
                'lib_path': 'wandb'},
  'syms': {'wandb.core': {'wandb.core.foo': ('core.html#foo', 'wandb/core.py')}}}
